###
# Install GeoServer from Custom GeoNode Build 
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: install Tomcat 
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
   - tomcat7

- name: copy the Tomcat setenv.sh file to /usr/share/tomcat7/bin
  template: src=setenv.sh dest=/usr/share/tomcat7/bin/setenv.sh
  sudo: yes

- name: copy the tomcat7 file to /etc/default
  template: src=tomcat7 dest=/etc/default/tomcat7
  sudo: yes

- name: Download Geoserver (remote)
  sudo: yes
  get_url:
    dest=/var/lib/tomcat7/webapps/geoserver.war
    url={{ geoserver_url }}
    owner=0
    group=0
    mode=0644

- name: Restart Tomcat
  service: name=tomcat7 state=restarted
  sudo: yes

